"""empty message

Revision ID: 044b32c8e3c5
Revises: dc82d4954d7d
Create Date: 2016-02-05 16:13:32.072593

"""

# revision identifiers, used by Alembic.
revision = '044b32c8e3c5'
down_revision = 'dc82d4954d7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
