"""empty message

Revision ID: 099f19bcc10e
Revises: fc61138564f8
Create Date: 2016-02-05 23:33:16.439557

"""

# revision identifiers, used by Alembic.
revision = '099f19bcc10e'
down_revision = 'fc61138564f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
