"""empty message

Revision ID: 0fba7fb2b3d4
Revises: 6f24b1909959
Create Date: 2016-02-05 13:27:19.466907

"""

# revision identifiers, used by Alembic.
revision = '0fba7fb2b3d4'
down_revision = '6f24b1909959'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeds')
    ### end Alembic commands ###
