"""empty message

Revision ID: 22d1ca567036
Revises: 099f19bcc10e
Create Date: 2016-02-09 09:09:06.992776

"""

# revision identifiers, used by Alembic.
revision = '22d1ca567036'
down_revision = '099f19bcc10e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('frequency', sa.Integer(), nullable=True))
    op.add_column('feeds', sa.Column('hashtag', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'hashtag')
    op.drop_column('feeds', 'frequency')
    ### end Alembic commands ###
