"""empty message

Revision ID: 6f24b1909959
Revises: d66f086b258
Create Date: 2016-02-04 16:49:57.590066

"""

# revision identifiers, used by Alembic.
revision = '6f24b1909959'
down_revision = 'd66f086b258'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('codepostal', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(length=15), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'codepostal')
    ### end Alembic commands ###
