"""empty message

Revision ID: 7d4111dbe579
Revises: 85f1335881b1
Create Date: 2016-02-05 14:45:49.487464

"""

# revision identifiers, used by Alembic.
revision = '7d4111dbe579'
down_revision = '85f1335881b1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feeds', 'users', ['user_id'], ['id'])
    op.drop_constraint(u'users_ibfk_2', 'users', type_='foreignkey')
    op.drop_column('users', 'feed_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('feed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_ibfk_2', 'users', 'feeds', ['feed_id'], ['id'])
    op.drop_constraint(None, 'feeds', type_='foreignkey')
    op.drop_column('feeds', 'user_id')
    ### end Alembic commands ###
