"""empty message

Revision ID: 85f1335881b1
Revises: 0fba7fb2b3d4
Create Date: 2016-02-05 13:41:59.495934

"""

# revision identifiers, used by Alembic.
revision = '85f1335881b1'
down_revision = '0fba7fb2b3d4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'feeds_ibfk_1', 'feeds', type_='foreignkey')
    op.drop_column('feeds', 'user_id')
    op.add_column('users', sa.Column('feed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'feeds', ['feed_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'feed_id')
    op.add_column('feeds', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'feeds_ibfk_1', 'feeds', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###
