"""empty message

Revision ID: c6fdacf1255a
Revises: 22d1ca567036
Create Date: 2016-02-09 09:24:37.508950

"""

# revision identifiers, used by Alembic.
revision = 'c6fdacf1255a'
down_revision = '22d1ca567036'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('Tweet_actif', sa.Boolean(), nullable=True))
    op.add_column('feeds', sa.Column('collect_actif', sa.Boolean(), nullable=True))
    op.drop_column('feeds', 'actif')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('actif', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('feeds', 'collect_actif')
    op.drop_column('feeds', 'Tweet_actif')
    ### end Alembic commands ###
