"""empty message

Revision ID: cc11541b02d2
Revises: c6fdacf1255a
Create Date: 2016-02-09 09:28:56.358827

"""

# revision identifiers, used by Alembic.
revision = 'cc11541b02d2'
down_revision = 'c6fdacf1255a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
