"""empty message

Revision ID: fc61138564f8
Revises: 65eec0dcbac1
Create Date: 2016-02-05 22:39:34.331976

"""

# revision identifiers, used by Alembic.
revision = 'fc61138564f8'
down_revision = '65eec0dcbac1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
